import { afterEach, describe, expect, it } from "vitest";
import { THINKING_ORDER, THINKING_LABEL_KEYS, resolveThinkingLevel } from "@shared/thinking-levels";
import { COMPACTION_SUMMARY_HEADER, compactionCardFields, compactionSummaryNotice } from "@shared/prompts";
import { uiI18n } from "./i18n";
import { thinkingLevelLabel, thinkingLevelOptions } from "./thinking-options";
import { displayCompactionSummary } from "../components/chat-utils";

afterEach(async () => { await uiI18n.changeLanguage("zh-CN"); });

describe("shared display data localization", () => {
  it("keeps supported levels and adaptation independent of translated labels", async () => {
    await uiI18n.changeLanguage("en");
    expect(thinkingLevelOptions(["high", "low"])).toEqual([{ value: "low", label: "Low" }, { value: "high", label: "High" }]);
    expect(thinkingLevelOptions(["off"])).toEqual([{ value: "off", label: "Off" }]);
    expect(thinkingLevelOptions([]).map(option => option.value)).toEqual(THINKING_ORDER);
    expect(thinkingLevelOptions(null).map(option => option.value)).toEqual(THINKING_ORDER);
    expect(resolveThinkingLevel("medium", ["high", "low"])).toBe("low");
    for (const level of THINKING_ORDER) {
      expect(uiI18n.exists(THINKING_LABEL_KEYS[level], { lng: "en" })).toBe(true);
      expect(uiI18n.exists(THINKING_LABEL_KEYS[level], { lng: "zh-CN" })).toBe(true);
    }
  });

  it("does not reinterpret unknown model identifiers as display keys", () => {
    expect(thinkingLevelLabel("vendor-specific-level")).toBe("vendor-specific-level");
    expect(thinkingLevelLabel("__proto__")).toBe("__proto__");
  });

  it("localizes the summary envelope without changing its original content or stored format", async () => {
    const original = `## 用户内容\n\n${COMPACTION_SUMMARY_HEADER}\n这是正文里的引用，不能删除。`;
    const stored = compactionSummaryNotice(original);
    expect(compactionCardFields(original).text).toBe(stored);
    await uiI18n.changeLanguage("en");
    const displayed = displayCompactionSummary(stored);
    expect(displayed).toBe(`【Context summary (generated by compaction; original text)】\n\n${original}`);
    expect(compactionSummaryNotice(original)).toBe(stored);
    await uiI18n.changeLanguage("zh-CN");
    expect(displayCompactionSummary(stored)).toBe(stored);
  });

  it("preserves a raw historical summary that has no generated envelope", async () => {
    await uiI18n.changeLanguage("en");
    const original = "原始摘要，不属于界面文案。";
    expect(displayCompactionSummary(original)).toBe(`【Context summary (generated by compaction; original text)】\n\n${original}`);
  });
});
