name: Build & Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: macos-latest
            name: macOS-arm64
          - os: macos-13
            name: macOS-x64
          - os: windows-latest
            name: Windows-x64
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - run: npm ci

      - name: Build
        run: npm run build
        env:
          CSC_IDENTITY_AUTO_DISCOVERY: "false"
          ELECTRON_BUILDER_SKIP_PUBLISH: "true"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: easymint-${{ matrix.name }}
          path: dist-electron/*.*
          if-no-files-found: ignore

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v4

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: easymint-*/*
          generate_release_notes: true
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
